export default {
    fire: require('../assets/fire.png'),
    question: require('../assets/question.png'),
    done: require('../assets/done.png'),
    check: require('../assets/check.png'),
    facebook: require('../assets/facebook.png'),
    instagram: require('../assets/instagram.png'),
    twitter: require('../assets/twitter.png'),
    menu: require('../assets/menu.png'),
    search: require('../assets/search.png'),
    heart: require("../assets/heart.png"),
    heartred: require("../assets/heartred.png"),
    star: require("../assets/star.png"),
    earth: require('../assets/earth.png'),
    angleRight: require('../assets/angle-right.png'),
    agriculture: require('../assets/agriculture.png'),
    setting: require('../assets/setting.png'),
    signOut: require('../assets/log-out.png'),
    smartphone: require('../assets/smartphone.png'),
    email: require('../assets/email.png'),
    taplock: require('../assets/tab.png'),
    padlock: require('../assets/padlock.png'),
    key: require('../assets/key.png'),
    switch: require('../assets/switch.png'),
    doc: require('../assets/docs.png'),
    settings: require('../assets/settings.png'),
    open: require('../assets/open.png'),
    plus: require('../assets/plus.png'),
    messenger: require('../assets/messenger.png'),

    instagramLogo: require('../assets/instagramLogo.png'),
    avt: require('../assets/avt.jpg'),
    ribbon: require('../assets/ribbon.png'),
    ins5: require('../assets/ins5.png'),
    ins2: require('../assets/ins2.png'),
    ins3: require('../assets/ins3.png'),
    ins4: require('../assets/ins4.png'),
    ins5: require('../assets/ins5.png'),
    ins6: require('../assets/ins6.png'),

}